cd ~/honeypot/scripts
cat > create_dynamic_files.py << 'EOF'
#!/usr/bin/env python3
"""
Créer des fichiers qui "apparaissent" de manière réaliste dans le temps
"""

import os
from datetime import datetime

HONEYFS = "/home/cowrie/cowrie/honeyfs"

def create_exam_results_file():
    """Crée un fichier de résultats d'examen pour aujourd'hui"""
    today = datetime.now().strftime("%Y-%m-%d")
    results_file = f"{HONEYFS}/home/p.adjanohoun/exam_results_{today}.txt"
    
    content = f"""EXAM RESULTS - {today}
======================
Generated by examination system
Status: PRELIMINARY - Do not distribute

Class: INFO301
Total Students: 24
Average Score: 76.5
Highest: 98 (Student 2024003)
Lowest: 52 (Student 2024012)

Distribution:
A (85+): 8 students
B (75-84): 10 students
C (65-74): 4 students
F (<65): 2 students

Next Review: {datetime.now().replace(day=28).strftime('%Y-%m-%d')}
"""
    
    os.makedirs(os.path.dirname(results_file), exist_ok=True)
    with open(results_file, "w") as f:
        f.write(content)
    
    print(f"[+] Fichier créé: {results_file}")

def create_admin_notes():
    """Crée des notes administratives"""
    notes_file = f"{HONEYFS}/root/admin_notes.txt"
    
    content = """ADMIN NOTES - CONFIDENTIAL
==========================

TODO:
- Update student database with new registrations
- Review server access logs for Q1
- Schedule maintenance window for Feb 10
- Prepare IT budget proposal for board meeting

Recent Issues:
- LDAP server performance degradation (Feb 1-3)
- Network interruption in Building C (Jan 28)
- Backup system failure - check tape rotation

Credentials to migrate:
- Old MySQL root password needs changing
- SSH keys for server replication need renewal

Next all-hands: Feb 15, 2pm
"""
    
    with open(notes_file, "w") as f:
        f.write(content)
    
    print(f"[+] Fichier créé: {notes_file}")

if __name__ == "__main__":
    create_exam_results_file()
    create_admin_notes()
    print("[✓] Fichiers dynamiques créés")
EOF

chmod +x create_dynamic_files.py
python3 create_dynamic_files.py
