"""
Detection rules module for the Dynamic Honeypot Platform.
Defines and manages detection rules for security event analysis.
"""

import re
from typing import Dict, List, Any, Optional, Callable
from dataclasses import dataclass, asdict
from utils.logger import get_logger
from utils.config_loader import ConfigLoader
from utils.date_utils import DateUtils


@dataclass
class DetectionRule:
    """Detection rule definition."""
    name: str
    enabled: bool
    severity: str
    description: str
    conditions: Dict[str, Any]
    alert: Dict[str, Any]
    rule_type: str = "pattern"


@dataclass
class Alert:
    """Security alert generated by detection engine."""
    alert_id: str
    timestamp: str
    rule_name: str
    severity: str
    source_ip: str
    event: Dict[str, Any]
    message: str
    confidence: float
    technique_candidates: List[str]
    metadata: Dict[str, Any]


class RuleEngine:
    """Manages and evaluates detection rules."""
    
    def __init__(self, config_dir: str = "config"):
        """
        Initialize rule engine.
        
        Args:
            config_dir: Directory containing configuration files
        """
        self.config_loader = ConfigLoader(config_dir)
        self.logger = get_logger("RuleEngine")
        
        # Load configuration
        self.detection_config = self.config_loader.load_yaml("detection_rules.yaml")
        self.settings = self.config_loader.load_settings("settings.yaml")
        
        # Parse rules
        self.rules: Dict[str, DetectionRule] = {}
        self._parse_rules()
        
        # Alert counter
        self.alert_counter = 0
    
    def _parse_rules(self):
        """Parse detection rules from configuration."""
        rules_config = self.detection_config.get('rules', {})
        
        for rule_name, rule_config in rules_config.items():
            try:
                rule = DetectionRule(
                    name=rule_name,
                    enabled=rule_config.get('enabled', True),
                    severity=rule_config.get('severity', 'medium'),
                    description=rule_config.get('description', ''),
                    conditions=rule_config.get('conditions', {}),
                    alert=rule_config.get('alert', {}),
                    rule_type=self._determine_rule_type(rule_config)
                )
                self.rules[rule_name] = rule
            except Exception as e:
                self.logger.error(f"Error parsing rule {rule_name}: {e}")
        
        self.logger.info(f"Loaded {len(self.rules)} detection rules")
    
    def _determine_rule_type(self, rule_config: Dict[str, Any]) -> str:
        """Determine rule type based on conditions."""
        conditions = rule_config.get('conditions', {})
        
        if 'event_type' in conditions:
            return 'event_type'
        elif 'event_patterns' in conditions:
            return 'pattern'
        elif 'command_patterns' in conditions:
            return 'command'
        elif 'file_patterns' in conditions:
            return 'file'
        elif 'http_patterns' in conditions:
            return 'http'
        elif 'sequence' in conditions:
            return 'sequence'
        else:
            return 'generic'
    
    def evaluate_event(self, event: Dict[str, Any]) -> List[Alert]:
        """
        Evaluate an event against all enabled rules.
        
        Args:
            event: Normalized event dictionary
            
        Returns:
            List of generated alerts
        """
        alerts = []
        
        for rule_name, rule in self.rules.items():
            if not rule.enabled:
                continue
            
            try:
                if self._evaluate_rule(event, rule):
                    alert = self._generate_alert(event, rule)
                    alerts.append(alert)
            except Exception as e:
                self.logger.error(f"Error evaluating rule {rule_name}: {e}")
        
        return alerts
    
    def _evaluate_rule(self, event: Dict[str, Any], rule: DetectionRule) -> bool:
        """
        Evaluate a single rule against an event.
        
        Args:
            event: Event dictionary
            rule: Detection rule
            
        Returns:
            True if rule matches
        """
        conditions = rule.conditions
        rule_type = rule.rule_type
        
        if rule_type == 'event_type':
            return self._evaluate_event_type_rule(event, conditions)
        elif rule_type == 'pattern':
            return self._evaluate_pattern_rule(event, conditions)
        elif rule_type == 'command':
            return self._evaluate_command_rule(event, conditions)
        elif rule_type == 'file':
            return self._evaluate_file_rule(event, conditions)
        elif rule_type == 'http':
            return self._evaluate_http_rule(event, conditions)
        elif rule_type == 'sequence':
            return self._evaluate_sequence_rule(event, conditions)
        else:
            return self._evaluate_generic_rule(event, conditions)
    
    def _evaluate_event_type_rule(self, event: Dict[str, Any], conditions: Dict[str, Any]) -> bool:
        """Evaluate event type based rule."""
        event_type = conditions.get('event_type')
        aggregation = conditions.get('aggregation')
        threshold = conditions.get('threshold', 1)
        window = conditions.get('window', 60)
        
        if event.get('event_type') != event_type:
            return False
        
        # For aggregation rules, we'd need to track event history
        # This is a simplified implementation
        if aggregation == 'count':
            # In a real implementation, this would check historical events
            return True
        
        return True
    
    def _evaluate_pattern_rule(self, event: Dict[str, Any], conditions: Dict[str, Any]) -> bool:
        """Evaluate pattern-based rule."""
        event_patterns = conditions.get('event_patterns', [])
        threshold = conditions.get('threshold', 1)
        
        match_count = 0
        for pattern in event_patterns:
            if self._matches_event_pattern(event, pattern):
                match_count += 1
        
        return match_count >= threshold
    
    def _matches_event_pattern(self, event: Dict[str, Any], pattern: str) -> bool:
        """Check if event matches a pattern."""
        # Pattern format: "event_type:specific_value"
        if ':' in pattern:
            event_type, specific_value = pattern.split(':', 1)
            event_value = event.get(event_type, '')
            return event_value and specific_value.lower() in str(event_value).lower()
        else:
            return event.get('event_type') == pattern
    
    def _evaluate_command_rule(self, event: Dict[str, Any], conditions: Dict[str, Any]) -> bool:
        """Evaluate command-based rule."""
        command_patterns = conditions.get('command_patterns', [])
        threshold = conditions.get('threshold', 1)
        
        command = event.get('command', '')
        if not command:
            return False
        
        match_count = 0
        for pattern in command_patterns:
            if pattern.lower() in command.lower():
                match_count += 1
        
        return match_count >= threshold
    
    def _evaluate_file_rule(self, event: Dict[str, Any], conditions: Dict[str, Any]) -> bool:
        """Evaluate file-based rule."""
        file_patterns = conditions.get('file_patterns', [])
        threshold = conditions.get('threshold', 1)
        
        # Check command and path for file patterns
        command = event.get('command', '')
        path = event.get('path', '')
        text_to_check = f"{command} {path}".lower()
        
        match_count = 0
        for pattern in file_patterns:
            if pattern.lower() in text_to_check:
                match_count += 1
        
        return match_count >= threshold
    
    def _evaluate_http_rule(self, event: Dict[str, Any], conditions: Dict[str, Any]) -> bool:
        """Evaluate HTTP-based rule."""
        http_patterns = conditions.get('http_patterns', [])
        threshold = conditions.get('threshold', 1)
        
        path = event.get('path', '')
        if not path:
            return False
        
        match_count = 0
        for pattern in http_patterns:
            if pattern.lower() in path.lower():
                match_count += 1
        
        return match_count >= threshold
    
    def _evaluate_sequence_rule(self, event: Dict[str, Any], conditions: Dict[str, Any]) -> bool:
        """Evaluate sequence-based rule."""
        # Sequence rules require tracking event history
        # This is a simplified implementation
        sequence = conditions.get('sequence', [])
        
        if not sequence:
            return False
        
        # Check if current event matches any in sequence
        for seq_event in sequence:
            if event.get('event_type') == seq_event.get('event_type'):
                return True
        
        return False
    
    def _evaluate_generic_rule(self, event: Dict[str, Any], conditions: Dict[str, Any]) -> bool:
        """Evaluate generic rule."""
        # Default to simple field matching
        for key, value in conditions.items():
            if key in ['threshold', 'window', 'aggregation']:
                continue
            if event.get(key) != value:
                return False
        return True
    
    def _generate_alert(self, event: Dict[str, Any], rule: DetectionRule) -> Alert:
        """
        Generate an alert from a matching rule.
        
        Args:
            event: Event dictionary
            rule: Detection rule
            
        Returns:
            Alert object
        """
        self.alert_counter += 1
        
        alert_config = rule.alert
        message = alert_config.get('message', '').format(
            source_ip=event.get('source_ip', 'unknown'),
            event_type=event.get('event_type', 'unknown'),
            command=event.get('command', ''),
            file_path=event.get('path', '')
        )
        
        return Alert(
            alert_id=f"alert_{self.alert_counter}",
            timestamp=DateUtils.to_iso_string(DateUtils.now()),
            rule_name=rule.name,
            severity=rule.severity,
            source_ip=event.get('source_ip', 'unknown'),
            event=event,
            message=message,
            confidence=alert_config.get('confidence', 0.7),
            technique_candidates=[],
            metadata={
                'rule_description': rule.description,
                'rule_type': rule.rule_type
            }
        )
    
    def evaluate_events_batch(self, events: List[Dict[str, Any]]) -> List[Alert]:
        """
        Evaluate a batch of events against rules.
        
        Args:
            events: List of normalized events
            
        Returns:
            List of generated alerts
        """
        all_alerts = []
        
        for event in events:
            try:
                alerts = self.evaluate_event(event)
                all_alerts.extend(alerts)
            except Exception as e:
                self.logger.error(f"Error evaluating event: {e}")
        
        self.logger.info(f"Generated {len(all_alerts)} alerts from {len(events)} events")
        return all_alerts
    
    def get_rule(self, rule_name: str) -> Optional[DetectionRule]:
        """
        Get a specific rule by name.
        
        Args:
            rule_name: Rule name
            
        Returns:
            DetectionRule or None if not found
        """
        return self.rules.get(rule_name)
    
    def get_all_rules(self) -> List[DetectionRule]:
        """Get all rules."""
        return list(self.rules.values())
    
    def get_enabled_rules(self) -> List[DetectionRule]:
        """Get only enabled rules."""
        return [rule for rule in self.rules.values() if rule.enabled]
    
    def enable_rule(self, rule_name: str) -> bool:
        """
        Enable a specific rule.
        
        Args:
            rule_name: Rule name
            
        Returns:
            True if successful
        """
        rule = self.rules.get(rule_name)
        if rule:
            rule.enabled = True
            self.logger.info(f"Enabled rule: {rule_name}")
            return True
        return False
    
    def disable_rule(self, rule_name: str) -> bool:
        """
        Disable a specific rule.
        
        Args:
            rule_name: Rule name
            
        Returns:
            True if successful
        """
        rule = self.rules.get(rule_name)
        if rule:
            rule.enabled = False
            self.logger.info(f"Disabled rule: {rule_name}")
            return True
        return False
    
    def get_statistics(self) -> Dict[str, Any]:
        """
        Get rule engine statistics.
        
        Returns:
            Dictionary with statistics
        """
        enabled_count = sum(1 for rule in self.rules.values() if rule.enabled)
        
        severity_counts = {}
        for rule in self.rules.values():
            severity = rule.severity
            severity_counts[severity] = severity_counts.get(severity, 0) + 1
        
        return {
            'total_rules': len(self.rules),
            'enabled_rules': enabled_count,
            'disabled_rules': len(self.rules) - enabled_count,
            'total_alerts_generated': self.alert_counter,
            'severity_distribution': severity_counts
        }